# Site settings
title: Zilong Wang
baseurl: ""
url: "https://zlwang-cs.github.io"
google_analytics: UA-155279785-1 # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Zilong Wang
  desc: Ph.D. student at UC San Diego
  email: zlwang@ucsd.edu
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: zlwang-cs
  google_plus:
  keybase:
  linkedin: 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: zlwang_cs
  instagram: zlw.lens
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/publication/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
